name: english_lettutor_app
description: Learn English Lettutor App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: "2.0.0"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  provider: ^6.0.1 # for State management
  intl: ^0.17.0
  shared_preferences: ^2.0.12
  fuzzy: ^0.4.0-nullsafety.0 #search
  auto_animated: ^3.0.1

  flutter_staggered_grid_view: ^0.4.1 #grid respose
  curved_navigation_bar: ^1.0.1 # navigation
  country_picker: ^2.0.8 #countries
  flutter_slidable: ^1.1.0 #swip to delete
  multi_select_flutter: ^4.0.0 #multi select item

  flutter_svg: ^0.23.0 # help us to use SVG in our app
  image_picker: ^0.8.4+4 #image and video picker
  video_player: ^2.2.7 #video player

  # view pdf
  syncfusion_flutter_pdfviewer: ^19.3.56-beta
  # download PDF
  http: ^0.13.4

  #firebase
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.3
  firebase_core: ^1.11.0

  #google analytics
  firebase_analytics: ^9.0.5

  #facebook
  flutter_facebook_auth: ^4.0.1

  #toast
  fluttertoast: ^8.0.8

  #jitsi
  jitsi_meet: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_launcher_icons: ^0.9.1

flutter_icons:
  image_path: "assets/images/large_logo.png"
  android: true
  ios: true

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
  
flutter_intl:
  enabled: true
